name: del-runs-comments
on: workflow_dispatch
jobs:
  runx:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: christosgalano/delete-workflow-runs@v1.0.0
        with:
          owner: uBlockOrigin
          repo: uAssets
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: on-issue-comment
          
          


    
    