on:
  issue_comment:
    types: created
jobs:
  check-if-bad-comment:
    name: delete bad comment
    runs-on: ubuntu-latest
    if: ( contains(github.event.comment.body, 'Download') || contains(github.event.comment.body, 'install') || contains(github.event.comment.body, 'mediafire') || contains(github.event.comment.body, 'changme') ) && contains(github.event.comment.body, 'gcc')
    permissions: write-all
    steps:
      - name: Delete comment
        run: |
          echo " ${{ github.event.comment.body }} "
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'delete-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}