name: Triage YouTube issues

on:
  issues:
    types: opened

jobs:
  check-if-youtube:
    name: Close as duplicate
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'youtube.com:') || startsWith(github.event.issue.title, 'music.youtube.com:')
    permissions:
      issues: write
    steps:
      - name: Add label
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          labels: 'duplicate'
      - name: Add comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          body: |
            Please respect what is asked in the issue template to not unduly burden volunteers.
            
            This is a `youtube.com` issue, see <https://github.com/uBlockOrigin/uAssets/issues/20586>.
      - name: Close issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          close-reason: not_planned
