name: Update 3rd-party assets (weekly)

on:
  schedule:
    - cron: "29 4 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write  # for Git to git push
    name: Update 3rd-party assets
    runs-on: ubuntu-latest
    steps:
      - name: Clone uAssets
        uses: actions/checkout@v3
      - name: Fetch 3rd-party assets
        run: |
          ./tools/update-3rdparties.sh
      - name: Commit changes, if any
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "github-actions bot"
            git config user.email "<>"
            git add -u thirdparties/
            git commit -m "Update all 3rd-party assets"
            git push origin master
          fi
